var annotated =
[
    [ "Json", "namespaceJson.html", "namespaceJson" ],
    [ "BmobCloud", "classBmobCloud.html", "classBmobCloud" ],
    [ "BmobCloudDelegate", "classBmobCloudDelegate.html", "classBmobCloudDelegate" ],
    [ "BmobCountDelegate", "classBmobCountDelegate.html", "classBmobCountDelegate" ],
    [ "BmobDeleteDelegate", "classBmobDeleteDelegate.html", "classBmobDeleteDelegate" ],
    [ "BmobEmailVerifyDelegate", "classBmobEmailVerifyDelegate.html", "classBmobEmailVerifyDelegate" ],
    [ "BmobFindDelegate", "classBmobFindDelegate.html", "classBmobFindDelegate" ],
    [ "BmobGetDelegate", "classBmobGetDelegate.html", "classBmobGetDelegate" ],
    [ "BmobJsonUtil", "classBmobJsonUtil.html", null ],
    [ "BmobLoginDelegate", "classBmobLoginDelegate.html", "classBmobLoginDelegate" ],
    [ "BmobObject", "classBmobObject.html", "classBmobObject" ],
    [ "BmobQuery", "classBmobQuery.html", "classBmobQuery" ],
    [ "BmobQueryInterafce", "classBmobQueryInterafce.html", "classBmobQueryInterafce" ],
    [ "BmobRequestSMSCodeDelegate", "classBmobRequestSMSCodeDelegate.html", "classBmobRequestSMSCodeDelegate" ],
    [ "BmobResetPasswordByCodeDelegate", "classBmobResetPasswordByCodeDelegate.html", "classBmobResetPasswordByCodeDelegate" ],
    [ "BmobResetPasswordDelegate", "classBmobResetPasswordDelegate.html", "classBmobResetPasswordDelegate" ],
    [ "BmobSaveDelegate", "classBmobSaveDelegate.html", "classBmobSaveDelegate" ],
    [ "BmobSDKInit", "classBmobSDKInit.html", null ],
    [ "BmobStaticsDelegate", "classBmobStaticsDelegate.html", "classBmobStaticsDelegate" ],
    [ "BmobStrUtil", "classBmobStrUtil.html", null ],
    [ "BmobUpdateDelegate", "classBmobUpdateDelegate.html", "classBmobUpdateDelegate" ],
    [ "BmobUser", "classBmobUser.html", "classBmobUser" ],
    [ "DefaultValueArrayAllocator", "classDefaultValueArrayAllocator.html", "classDefaultValueArrayAllocator" ],
    [ "DefaultValueMapAllocator", "classDefaultValueMapAllocator.html", "classDefaultValueMapAllocator" ],
    [ "GameScore", "classGameScore.html", "classGameScore" ]
];