Cocos2dx SDK: BmobObject Class Reference
BmobObject Class Reference
Public Member Functions
BmobObject (string tableName)
virtual ~BmobObject ()
virtual void save (BmobSaveDelegate *delegate)
virtual void increment (string column, int value=1)
void setValue (string key, cocos2d::CCObject *object)
void setValue (string key, cocos2d::CCArray *array)
virtual void update (string objectId, BmobUpdateDelegate *delegate)
virtual void update (BmobUpdateDelegate *delegate)
virtual void remove (string name)
virtual void removeAll (string name, CCArray *array)
virtual void del (BmobDeleteDelegate *delegate)
virtual void del (string objectId, BmobDeleteDelegate *delegate)
virtual void add (string column, CCObject *object)
virtual void add (string column, CCArray *array)
void enParamsToHttp (std::string key, cocos2d::CCObject *object)
virtual void setHeader (vector< string > v)
virtual vector< string > getHeader ()
virtual CCObject * getParams (string key)
virtual void enJson (Json::Value *value)
virtual void deJson (Json::Value *value)
void clear ()
void send ()
void send (network::HttpRequest::Type type)
virtual void onHttpRequestCompleted (cocos2d::CCNode *pSender, void *data)
BmobObject (string tableName)
virtual void save (BmobSaveDelegate *delegate)
virtual void increment (string column, int value=1)
void setValue (string key, cocos2d::CCObject *object)
void setValue (string key, cocos2d::CCArray *array)
virtual void update (string objectId, BmobUpdateDelegate *delegate)
virtual void update (BmobUpdateDelegate *delegate)
virtual void remove (string name)
virtual void removeAll (string name, CCArray *array)
virtual void del (BmobDeleteDelegate *delegate)
virtual void del (string objectId, BmobDeleteDelegate *delegate)
virtual void add (string column, CCObject *object)
virtual void add (string column, CCArray *array)
void enParamsToHttp (std::string key, cocos2d::CCObject *object)
virtual void setHeader (std::vector< string > v)
virtual vector< string > getHeader ()
virtual CCObject * getParams (string key)
virtual void enJson (Json::Value *value)
virtual void deJson (Json::Value *value)
void clear ()
void send ()
void send (network::HttpRequest::Type type)
virtual void onHttpRequestCompleted (cocos2d::CCNode *pSender, void *data)
Protected Types
enum HTTP_OP_Type {
_bHTTP_SAVE, _bHTTP_UPDATE, _bHTTP_DELETE, _bHTTP_RESET,
_bHTTP_REQUEST_CODE, _bHTTP_RESET_BY_CODE, _bHTTP_EMAIL_VERIFY, _bHTTP_LOGIN,
_bHTTP_SAVE, _bHTTP_UPDATE, _bHTTP_DELETE, _bHTTP_RESET,
_bHTTP_REQUEST_CODE, _bHTTP_RESET_BY_CODE, _bHTTP_EMAIL_VERIFY, _bHTTP_LOGIN
}
enum HTTP_OP_Type {
_bHTTP_SAVE, _bHTTP_UPDATE, _bHTTP_DELETE, _bHTTP_RESET,
_bHTTP_REQUEST_CODE, _bHTTP_RESET_BY_CODE, _bHTTP_EMAIL_VERIFY, _bHTTP_LOGIN,
_bHTTP_SAVE, _bHTTP_UPDATE, _bHTTP_DELETE, _bHTTP_RESET,
_bHTTP_REQUEST_CODE, _bHTTP_RESET_BY_CODE, _bHTTP_EMAIL_VERIFY, _bHTTP_LOGIN
}
Protected Member Functions
CC_SYNTHESIZE (string, m_objectId, ObjectId)
CC_SYNTHESIZE (string, m_createdAt, CreatedAt)
CC_SYNTHESIZE (string, m_updatedAt, UpdatedAt)
CC_SYNTHESIZE (string, m_ACL, ACL)
CC_SYNTHESIZE (string, m_url, Url)
CC_SYNTHESIZE (string, m_tableName, TableName)
CC_SYNTHESIZE (string, m_session, Session)
CC_SYNTHESIZE (BmobSaveDelegate *, m_pSaveDelegate, SaveDelegate)
CC_SYNTHESIZE (BmobUpdateDelegate *, m_pUpdateDelegate, UpdateDelegate)
CC_SYNTHESIZE (BmobDeleteDelegate *, m_pDeleteDelegate, DeleteDelegate)
CC_SYNTHESIZE (BmobResetPasswordDelegate *, m_pResetDelegate, ResetDelegate)
CC_SYNTHESIZE (BmobRequestSMSCodeDelegate *, m_pRequestSMSCodeDelegate, RequestSMSCodeDelegate)
CC_SYNTHESIZE (BmobResetPasswordByCodeDelegate *, m_pResetByMSMCodeDelegate, ResetByMSMCodeDelegate)
CC_SYNTHESIZE (BmobEmailVerifyDelegate *, m_pEmailVerifyDelegate, EmailVerifyDelegate)
CC_SYNTHESIZE (BmobLoginDelegate *, m_pLoginDelegate, LoginDelegate)
CC_SYNTHESIZE (std::string, m_objectId, ObjectId)
CC_SYNTHESIZE (std::string, m_createdAt, CreatedAt)
CC_SYNTHESIZE (std::string, m_updatedAt, UpdatedAt)
CC_SYNTHESIZE (std::string, m_ACL, ACL)
CC_SYNTHESIZE (string, m_url, Url)
CC_SYNTHESIZE (std::string, m_tableName, TableName)
CC_SYNTHESIZE (string, m_session, Session)
CC_SYNTHESIZE (BmobSaveDelegate *, m_pSaveDelegate, SaveDelegate)
CC_SYNTHESIZE (BmobUpdateDelegate *, m_pUpdateDelegate, UpdateDelegate)
CC_SYNTHESIZE (BmobDeleteDelegate *, m_pDeleteDelegate, DeleteDelegate)
CC_SYNTHESIZE (BmobResetPasswordDelegate *, m_pResetDelegate, ResetDelegate)
CC_SYNTHESIZE (BmobRequestSMSCodeDelegate *, m_pRequestSMSCodeDelegate, RequestSMSCodeDelegate)
CC_SYNTHESIZE (BmobResetPasswordByCodeDelegate *, m_pResetByMSMCodeDelegate, ResetByMSMCodeDelegate)
CC_SYNTHESIZE (BmobEmailVerifyDelegate *, m_pEmailVerifyDelegate, EmailVerifyDelegate)
CC_SYNTHESIZE (BmobLoginDelegate *, m_pLoginDelegate, LoginDelegate)
Protected Attributes
HTTP_OP_Type _opType
std::map< string,
cocos2d::CCObject * > m_mapData
std::vector< string > m_header
std::map< std::string, CCObject * > m_mapData
std::vector< std::string > m_header
Detailed Description
Definition at line 23 of file bmobobject.h.
Member Enumeration Documentation
enum BmobObject::HTTP_OP_Type strong protected
save,update,delete's sign
Definition at line 28 of file bmobobject.h.
enum BmobObject::HTTP_OP_Type strong protected
save,update,delete's sign HTTP操作的类型，对应的是回调接口类型
Definition at line 29 of file bmobobject.h.
Constructor & Destructor Documentation
BmobObject::BmobObject (string tableName)
使用对象名来构造函数，也就是后台对应的表名
Parameters
tableName 对象表名
Definition at line 17 of file bmobobject.cpp.
References BmobObject().
Referenced by BmobObject().
BmobObject::~BmobObject () virtual
虚构函数
Definition at line 25 of file bmobobject.cpp.
Member Function Documentation
virtual void BmobObject::add (string column, CCObject * object) virtual
add alone object to list
virtual void BmobObject::add (string column, CCArray * array) virtual
add more object to list
void BmobObject::add (string column, CCObject * object) virtual
向BmobSDK中添加包含一个数据的数组
Parameters
column 字段名
object 对应字段名的值
Definition at line 138 of file bmobobject.cpp.
void BmobObject::add (string column, CCArray * array) virtual
向BmobSDK中添加包含多个数据的数组
Parameters
column 要添加的字段名
array 要添加的数组值
Definition at line 156 of file bmobobject.cpp.
void BmobObject::clear () inline
清楚请求中的数据
Definition at line 157 of file bmobobject.h.
Referenced by BmobUser::login(), BmobUser::loginByAccount(), BmobUser::loginBySMSCode(), BmobUser::requestEmailVerify(), BmobUser::requestSMSCode(), BmobUser::resetPasswordByEmail(), BmobUser::resetPasswordBySMSCode(), and BmobUser::updateCurrentUserPassword().
virtual void BmobObject::deJson (Json::Value * value) virtual
will json switch to map
void BmobObject::deJson (Json::Value * value) virtual
将Json数据解压成map<string,CCObject*>
Parameters
value 要解析的Json数据
Definition at line 220 of file bmobobject.cpp.
void BmobObject::del (BmobDeleteDelegate * delegate) virtual
删除BmobSDK后台数据
Parameters
delegate 删除数据回调接口
Definition at line 125 of file bmobobject.cpp.
void BmobObject::del (string objectId, BmobDeleteDelegate * delegate) virtual
直接使用objectId来删除数据
Parameters
objectId 要删除数据对应的ObjectID
delegate 删除数据的回调接口
Definition at line 133 of file bmobobject.cpp.
virtual void BmobObject::enJson (Json::Value * value) virtual
will property switch to json
void BmobObject::enJson (Json::Value * value) virtual
将发送给服务端数据转换成json数据
Parameters
value
Definition at line 216 of file bmobobject.cpp.
void BmobObject::enParamsToHttp (std::string key, cocos2d::CCObject * object)
将对象需要保存的数据压到HTTP请求中
Parameters
key 要在后台保存的字段
object 要在后台保存的字段对应的值
Referenced by BmobUser::requestEmailVerify(), BmobUser::requestSMSCode(), BmobUser::resetPasswordByEmail(), BmobUser::resetPasswordBySMSCode(), and BmobUser::updateCurrentUserPassword().
vector< string > BmobObject::getHeader () virtual
获取当前HTTP请求的头部
Definition at line 191 of file bmobobject.cpp.
virtual CCObject* BmobObject::getParams (string key) virtual
will propety add to m_mapData
CCObject * BmobObject::getParams (string key) virtual
获取key对应的数据
Parameters
key 字段名
Definition at line 178 of file bmobobject.cpp.
virtual void BmobObject::increment (string column, int value = 1) virtual
update
void BmobObject::increment (string column, int value = 1) virtual
更新对象调用方法
Parameters
column 更新的字段名或者列名
value 要更新的值，默认增加1 该方法值针对整型数据进行操作
Definition at line 44 of file bmobobject.cpp.
virtual void BmobObject::onHttpRequestCompleted (cocos2d::CCNode * pSender, void * data) virtual
callback of http request
void BmobObject::onHttpRequestCompleted (cocos2d::CCNode * pSender, void * data) virtual
HTTP请求回调函数
Parameters
pSender
data 回调返回数据
Definition at line 256 of file bmobobject.cpp.
References Json::Reader::parse().
virtual void BmobObject::remove (string name) virtual
delete
void BmobObject::remove (string name) virtual
设置要移除后台数据对应的字段
Parameters
name 字段名
Definition at line 94 of file bmobobject.cpp.
void BmobObject::removeAll (string name, CCArray * array) virtual
设置要移除后台数据对应的字段
Parameters
array 要移除的字段数组
Definition at line 109 of file bmobobject.cpp.
virtual void BmobObject::save (BmobSaveDelegate * delegate) virtual
BmobSaveDelegate save object
void BmobObject::save (BmobSaveDelegate * delegate) virtual
调用该方法将对象数据保存到SDK后台
Parameters
delegate 保存对象回调接口
Definition at line 29 of file bmobobject.cpp.
References BmobSDKInit::isInitialize().
void BmobObject::send ()
send data or request to server
void BmobObject::send ()
发送请求给BmobSDK后台
Definition at line 228 of file bmobobject.cpp.
Referenced by BmobUser::login(), BmobUser::loginByAccount(), BmobUser::loginBySMSCode(), BmobUser::requestEmailVerify(), BmobUser::requestSMSCode(), BmobUser::resetPasswordByEmail(), BmobUser::resetPasswordBySMSCode(), BmobUser::signUp(), BmobUser::update(), and BmobUser::updateCurrentUserPassword().
void BmobObject::send (network::HttpRequest::Type type)
使用HTTP类型发送请求
Parameters
type http请求类型,GET、POST、PUT、DELETE etc.
void BmobObject::setHeader (std::vector< string > v) virtual
about http header
Definition at line 178 of file bmobobject.cpp.
void BmobObject::setHeader (vector< string > v) virtual
设置HTTP请求的头部
Parameters
v 自定义HTTP的头部
Definition at line 187 of file bmobobject.cpp.
void BmobObject::setValue (string key, cocos2d::CCObject * object)
设置要更新的字段和值
Parameters
key 设置的字段名或者列名
object 需要设置的值
Definition at line 48 of file bmobobject.cpp.
void BmobObject::setValue (string key, cocos2d::CCArray * array)
对数组的操作
Parameters
key 要设置的字段名或者列名
array 数组值
void BmobObject::update (string objectId, BmobUpdateDelegate * delegate) virtual
使用objectId更新BmobSDK后台数据
Parameters
ObjectId 更新数据对应的objectId
delegate 更新数据回调接口
Reimplemented in BmobUser, and BmobUser.
Definition at line 74 of file bmobobject.cpp.
void BmobObject::update (BmobUpdateDelegate * delegate) virtual
更新BmobSDK后台数据
Parameters
delegate 更新数据回调接口
Reimplemented in BmobUser, and BmobUser.
Definition at line 69 of file bmobobject.cpp.
The documentation for this class was generated from the following files:
baseobject/bmobobject.h
baseobject/bmobobject.cpp