Cocos2dx SDK: BmobUser Class Reference
BmobUser Class Reference
Public Member Functions
virtual void signUp (BmobSaveDelegate *delegate)
virtual void login (BmobSaveDelegate *delegate)
virtual void update (string objectId, BmobUpdateDelegate *delegate)
virtual void update (BmobUpdateDelegate *delegate)
void resetPasswordByEmail (string email, BmobResetPasswordDelegate *delegate)
void requestSMSCode (string meblieNumber, string template_name, BmobRequestSMSCodeDelegate *delegate)
void resetPasswordBySMSCode (string pw, string code, BmobResetPasswordByCodeDelegate *delegate)
void updateCurrentUserPassword (string old_pwd, string new_pwd, BmobUpdateDelegate *delegate)
void requestEmailVerify (string email, BmobEmailVerifyDelegate *delegate)
void loginByAccount (string mebileNumber, string pwd, BmobLoginDelegate *delegate)
void loginBySMSCode (string mebileNumber, string code, BmobLoginDelegate *delegate)
void signOrLoginByMobilePhone (string mebileNumber, string code, BmobLoginDelegate *delegate)
string getPassword ()
void setPassword (string password)
virtual void signUp (BmobSaveDelegate *delegate)
virtual void login (BmobSaveDelegate *delegate)
virtual void update (string objectId, BmobUpdateDelegate *delegate)
virtual void update (BmobUpdateDelegate *delegate)
void resetPasswordByEmail (string email, BmobResetPasswordDelegate *delegate)
void requestSMSCode (string meblieNumber, string template_name, BmobRequestSMSCodeDelegate *delegate)
void resetPasswordBySMSCode (string pw, string code, BmobResetPasswordByCodeDelegate *delegate)
void updateCurrentUserPassword (string old_pwd, string new_pwd, BmobUpdateDelegate *delegate)
void requestEmailVerify (string email, BmobEmailVerifyDelegate *delegate)
void loginByAccount (string mebileNumber, string pwd, BmobLoginDelegate *delegate)
void loginBySMSCode (string mebileNumber, string code, BmobLoginDelegate *delegate)
void signOrLoginByMobilePhone (string mebileNumber, string code, BmobLoginDelegate *delegate)
string getPassword ()
void setPassword (string password)
Public Member Functions inherited from BmobObject
BmobObject (string tableName)
virtual ~BmobObject ()
virtual void save (BmobSaveDelegate *delegate)
virtual void increment (string column, int value=1)
void setValue (string key, cocos2d::CCObject *object)
void setValue (string key, cocos2d::CCArray *array)
virtual void remove (string name)
virtual void removeAll (string name, CCArray *array)
virtual void del (BmobDeleteDelegate *delegate)
virtual void del (string objectId, BmobDeleteDelegate *delegate)
virtual void add (string column, CCObject *object)
virtual void add (string column, CCArray *array)
void enParamsToHttp (std::string key, cocos2d::CCObject *object)
virtual void setHeader (vector< string > v)
virtual vector< string > getHeader ()
virtual CCObject * getParams (string key)
virtual void enJson (Json::Value *value)
virtual void deJson (Json::Value *value)
void clear ()
void send ()
void send (network::HttpRequest::Type type)
virtual void onHttpRequestCompleted (cocos2d::CCNode *pSender, void *data)
BmobObject (string tableName)
virtual void save (BmobSaveDelegate *delegate)
virtual void increment (string column, int value=1)
void setValue (string key, cocos2d::CCObject *object)
void setValue (string key, cocos2d::CCArray *array)
virtual void remove (string name)
virtual void removeAll (string name, CCArray *array)
virtual void del (BmobDeleteDelegate *delegate)
virtual void del (string objectId, BmobDeleteDelegate *delegate)
virtual void add (string column, CCObject *object)
virtual void add (string column, CCArray *array)
void enParamsToHttp (std::string key, cocos2d::CCObject *object)
virtual void setHeader (std::vector< string > v)
virtual vector< string > getHeader ()
virtual CCObject * getParams (string key)
virtual void enJson (Json::Value *value)
virtual void deJson (Json::Value *value)
void clear ()
void send ()
void send (network::HttpRequest::Type type)
virtual void onHttpRequestCompleted (cocos2d::CCNode *pSender, void *data)
Static Public Member Functions
static BmobUser * getCurrentUser ()
static void logOut ()
static BmobUser * getCurrentUser ()
static void logOut ()
Static Public Attributes
static BmobUser * currentUser = NULL
static string __USER_FILE = "cur_user.xml"
Additional Inherited Members
Protected Types inherited from BmobObject
enum HTTP_OP_Type {
_bHTTP_SAVE, _bHTTP_UPDATE, _bHTTP_DELETE, _bHTTP_RESET,
_bHTTP_REQUEST_CODE, _bHTTP_RESET_BY_CODE, _bHTTP_EMAIL_VERIFY, _bHTTP_LOGIN,
_bHTTP_SAVE, _bHTTP_UPDATE, _bHTTP_DELETE, _bHTTP_RESET,
_bHTTP_REQUEST_CODE, _bHTTP_RESET_BY_CODE, _bHTTP_EMAIL_VERIFY, _bHTTP_LOGIN
}
enum HTTP_OP_Type {
_bHTTP_SAVE, _bHTTP_UPDATE, _bHTTP_DELETE, _bHTTP_RESET,
_bHTTP_REQUEST_CODE, _bHTTP_RESET_BY_CODE, _bHTTP_EMAIL_VERIFY, _bHTTP_LOGIN,
_bHTTP_SAVE, _bHTTP_UPDATE, _bHTTP_DELETE, _bHTTP_RESET,
_bHTTP_REQUEST_CODE, _bHTTP_RESET_BY_CODE, _bHTTP_EMAIL_VERIFY, _bHTTP_LOGIN
}
Protected Member Functions inherited from BmobObject
CC_SYNTHESIZE (string, m_objectId, ObjectId)
CC_SYNTHESIZE (string, m_createdAt, CreatedAt)
CC_SYNTHESIZE (string, m_updatedAt, UpdatedAt)
CC_SYNTHESIZE (string, m_ACL, ACL)
CC_SYNTHESIZE (string, m_url, Url)
CC_SYNTHESIZE (string, m_tableName, TableName)
CC_SYNTHESIZE (string, m_session, Session)
CC_SYNTHESIZE (BmobSaveDelegate *, m_pSaveDelegate, SaveDelegate)
CC_SYNTHESIZE (BmobUpdateDelegate *, m_pUpdateDelegate, UpdateDelegate)
CC_SYNTHESIZE (BmobDeleteDelegate *, m_pDeleteDelegate, DeleteDelegate)
CC_SYNTHESIZE (BmobResetPasswordDelegate *, m_pResetDelegate, ResetDelegate)
CC_SYNTHESIZE (BmobRequestSMSCodeDelegate *, m_pRequestSMSCodeDelegate, RequestSMSCodeDelegate)
CC_SYNTHESIZE (BmobResetPasswordByCodeDelegate *, m_pResetByMSMCodeDelegate, ResetByMSMCodeDelegate)
CC_SYNTHESIZE (BmobEmailVerifyDelegate *, m_pEmailVerifyDelegate, EmailVerifyDelegate)
CC_SYNTHESIZE (BmobLoginDelegate *, m_pLoginDelegate, LoginDelegate)
CC_SYNTHESIZE (std::string, m_objectId, ObjectId)
CC_SYNTHESIZE (std::string, m_createdAt, CreatedAt)
CC_SYNTHESIZE (std::string, m_updatedAt, UpdatedAt)
CC_SYNTHESIZE (std::string, m_ACL, ACL)
CC_SYNTHESIZE (string, m_url, Url)
CC_SYNTHESIZE (std::string, m_tableName, TableName)
CC_SYNTHESIZE (string, m_session, Session)
CC_SYNTHESIZE (BmobSaveDelegate *, m_pSaveDelegate, SaveDelegate)
CC_SYNTHESIZE (BmobUpdateDelegate *, m_pUpdateDelegate, UpdateDelegate)
CC_SYNTHESIZE (BmobDeleteDelegate *, m_pDeleteDelegate, DeleteDelegate)
CC_SYNTHESIZE (BmobResetPasswordDelegate *, m_pResetDelegate, ResetDelegate)
CC_SYNTHESIZE (BmobRequestSMSCodeDelegate *, m_pRequestSMSCodeDelegate, RequestSMSCodeDelegate)
CC_SYNTHESIZE (BmobResetPasswordByCodeDelegate *, m_pResetByMSMCodeDelegate, ResetByMSMCodeDelegate)
CC_SYNTHESIZE (BmobEmailVerifyDelegate *, m_pEmailVerifyDelegate, EmailVerifyDelegate)
CC_SYNTHESIZE (BmobLoginDelegate *, m_pLoginDelegate, LoginDelegate)
Protected Attributes inherited from BmobObject
HTTP_OP_Type _opType
std::map< string,
cocos2d::CCObject * > m_mapData
std::vector< string > m_header
std::map< std::string, CCObject * > m_mapData
std::vector< std::string > m_header
Detailed Description
Definition at line 16 of file bmobuser.h.
Member Function Documentation
BmobUser * BmobUser::getCurrentUser () static
Definition at line 11 of file bmobuser.cpp.
void BmobUser::login (BmobSaveDelegate * delegate) virtual
Parameters
delegate
save user
Definition at line 94 of file bmobuser.cpp.
References BmobObject::clear(), and BmobObject::send().
void BmobUser::loginByAccount (string mebileNumber, string pwd, BmobLoginDelegate * delegate)
Parameters
meblieNumber ..
pwd
save user
Definition at line 119 of file bmobuser.cpp.
References BmobObject::clear(), and BmobObject::send().
void BmobUser::loginBySMSCode (string mebileNumber, string code, BmobLoginDelegate * delegate)
SMS
Parameters
mebileNumber
code SMS
delegate
save user
Definition at line 145 of file bmobuser.cpp.
References BmobObject::clear(), and BmobObject::send().
Referenced by signOrLoginByMobilePhone().
void BmobUser::logOut () static
Definition at line 38 of file bmobuser.cpp.
void BmobUser::requestEmailVerify (string email, BmobEmailVerifyDelegate * delegate)
Parameters
email
delegate
Definition at line 303 of file bmobuser.cpp.
References BmobObject::clear(), BmobObject::enParamsToHttp(), and BmobObject::send().
void BmobUser::requestSMSCode (string meblieNumber, string template_name, BmobRequestSMSCodeDelegate * delegate)
SMS
Parameters
meblieNumber
template_name
delegate
Definition at line 228 of file bmobuser.cpp.
References BmobObject::clear(), BmobObject::enParamsToHttp(), and BmobObject::send().
void BmobUser::resetPasswordByEmail (string email, BmobResetPasswordDelegate * delegate)
Parameters
email
delegate
Definition at line 210 of file bmobuser.cpp.
References BmobObject::clear(), BmobObject::enParamsToHttp(), and BmobObject::send().
void BmobUser::resetPasswordBySMSCode (string pw, string code, BmobResetPasswordByCodeDelegate * delegate)
SMS
Parameters
pw
code SMS
delegate
Definition at line 251 of file bmobuser.cpp.
References BmobObject::clear(), BmobObject::enParamsToHttp(), and BmobObject::send().
void BmobUser::signOrLoginByMobilePhone (string mebileNumber, string code, BmobLoginDelegate * delegate)
Parameters
mebileNumber
code SMS
delegate
Definition at line 171 of file bmobuser.cpp.
References loginBySMSCode().
void BmobUser::signUp (BmobSaveDelegate * delegate) virtual
Parameters
delegate
save user
Definition at line 72 of file bmobuser.cpp.
References BmobObject::send().
virtual void BmobUser::update (string objectId, BmobUpdateDelegate * delegate) virtual
objectIdBmobSDK
Parameters
ObjectId objectId
delegate
Reimplemented from BmobObject.
virtual void BmobUser::update (BmobUpdateDelegate * delegate) virtual
BmobSDK
Parameters
delegate
Reimplemented from BmobObject.
void BmobUser::update (string objectId, BmobUpdateDelegate * delegate) virtual
objectId
Parameters
objectId objectId
Reimplemented from BmobObject.
Definition at line 175 of file bmobuser.cpp.
References BmobObject::send().
Referenced by update().
void BmobUser::update (BmobUpdateDelegate * delegate) virtual
Parameters
delegate
Reimplemented from BmobObject.
Definition at line 206 of file bmobuser.cpp.
References update().
void BmobUser::updateCurrentUserPassword (string old_pwd, string new_pwd, BmobUpdateDelegate * delegate)
Parameters
old_pwd
new_pwd
delegate
Definition at line 271 of file bmobuser.cpp.
References BmobObject::clear(), BmobObject::enParamsToHttp(), and BmobObject::send().
The documentation for this class was generated from the following files:
baseobject/bmobuser.h
baseobject/bmobuser.cpp