Cocos2dx SDK: BmobQuery Class Reference
BmobQuery Class Reference
Public Member Functions
BmobQuery (string tableName)
virtual void findObjects (BmobFindDelegate *delegate)
virtual void findObjects (string tableName, BmobFindDelegate *delegate)
virtual void getObject (string objectId, BmobGetDelegate *delegate)
virtual void count (BmobCountDelegate *delegate, bool sign=false)
virtual void findStatistics (BmobStaticsDelegate *delegate)
virtual void addWhereEqualTo (string seg, CCObject *object)
virtual void addWhereNotEqualTo (string seg, CCObject *object)
virtual void addWhereGreatorThan (string seg, CCObject *object)
virtual void addWhereLessThan (string seg, CCObject *object)
virtual void addWhereLessThanOrEqualTo (string seg, CCObject *object)
virtual void addWhereGreaterThan (string seg, CCObject *object)
virtual void addWhereGreaterThanOrEqualTo (string seg, CCObject *object)
virtual void addWhereContainedIn (string seg, CCObject *array)
virtual void addWhereNotContainedIn (string seg, CCObject *array)
virtual void addWhereContainsAll (string seg, CCArray *array)
virtual void addWhereExists (string column)
virtual void addWhereDoesNotExists (string column)
virtual void addWhereMatches ()
virtual void addWhereContains ()
virtual void whereStartsWith ()
virtual void whereEndsWith ()
virtual void setLimit (int limit)
virtual void setSkip (int skip)
virtual void order (string key)
virtual void setCachePolicy ()
virtual bool hasCachedResult ()
virtual void clearCachedResult ()
virtual void clearAllCachedResults ()
virtual void addQueryKeys (string column)
virtual void sum (string column)
virtual void average (string column)
virtual void max (string column)
virtual void min (string column)
virtual void groupby (string column)
virtual void having (bool isHaving=false)
virtual void setHasGroupCount (bool groupCount)
virtual void setHeader (vector< string > v)
virtual vector< string > getHeader ()
virtual void enJson (Json::Value *value)
virtual void deJson (Json::Value *value)
BmobQuery (string tableName)
virtual void findObjects (BmobFindDelegate *delegate)
virtual void findObjects (string tableName, BmobFindDelegate *delegate)
virtual void getObject (string objectId, BmobGetDelegate *delegate)
virtual void count (BmobCountDelegate *delegate, bool sign=false)
virtual void findStatistics (BmobStaticsDelegate *delegate)
virtual void addWhereEqualTo (string seg, CCObject *object)
virtual void addWhereNotEqualTo (string seg, CCObject *object)
virtual void addWhereGreatorThan (string seg, CCObject *object)
virtual void addWhereLessThan (string seg, CCObject *object)
virtual void addWhereLessThanOrEqualTo (string seg, CCObject *object)
virtual void addWhereGreaterThan (string seg, CCObject *object)
virtual void addWhereGreaterThanOrEqualTo (string seg, CCObject *object)
virtual void addWhereContainedIn (string seg, CCObject *array)
virtual void addWhereNotContainedIn (string seg, CCObject *array)
virtual void addWhereContainsAll (string seg, CCArray *array)
virtual void addWhereExists (string column)
virtual void addWhereDoesNotExists (string column)
virtual void addWhereMatches ()
virtual void addWhereContains ()
virtual void whereStartsWith ()
virtual void whereEndsWith ()
virtual void setLimit (int limit)
virtual void setSkip (int skip)
virtual void order (string key)
virtual void setCachePolicy ()
virtual bool hasCachedResult ()
virtual void clearCachedResult ()
virtual void clearAllCachedResults ()
virtual void addQueryKeys (string column)
virtual void sum (string column)
virtual void average (string column)
virtual void max (string column)
virtual void min (string column)
virtual void groupby (string column)
virtual void having (bool isHaving=false)
virtual void setHasGroupCount (bool groupCount)
virtual void setHeader (vector< string > v)
virtual vector< string > getHeader ()
virtual void enJson (Json::Value *value)
virtual void deJson (Json::Value *value)
Public Member Functions inherited from BmobQueryInterafce
BmobQueryInterafce (string tableName)
void setQueryType (BmobQueryInterafce::Type type)
BmobQueryInterafce::Type getQueryType ()
void clear ()
BmobQueryInterafce (string tableName)
void setQueryType (BmobQueryInterafce::Type type)
BmobQueryInterafce::Type getQueryType ()
void clear ()
Protected Member Functions
virtual void onHttpRequestCompleted (cocos2d::CCNode *pSender, void *data)
virtual void query ()
virtual void onHttpRequestCompleted (cocos2d::CCNode *pSender, void *data)
virtual void query ()
Protected Member Functions inherited from BmobQueryInterafce
CC_SYNTHESIZE (string, m_objectId, ObjectId)
CC_SYNTHESIZE (string, m_tableName, TableName)
CC_SYNTHESIZE (BmobFindDelegate *, m_pFindDelegate, FindDelegate)
CC_SYNTHESIZE (BmobGetDelegate *, m_pGetDelegate, GetDelegate)
CC_SYNTHESIZE (BmobCountDelegate *, m_pCountDelegate, CountDelegate)
CC_SYNTHESIZE (BmobStaticsDelegate *, m_pStaticsDelegate, StaticDelegate)
CC_SYNTHESIZE (string, m_objectId, ObjectId)
CC_SYNTHESIZE (string, m_tableName, TableName)
CC_SYNTHESIZE (BmobFindDelegate *, m_pFindDelegate, FindDelegate)
CC_SYNTHESIZE (BmobGetDelegate *, m_pGetDelegate, GetDelegate)
CC_SYNTHESIZE (BmobCountDelegate *, m_pCountDelegate, CountDelegate)
CC_SYNTHESIZE (BmobStaticsDelegate *, m_pStaticsDelegate, StaticDelegate)
Additional Inherited Members
Public Types inherited from BmobQueryInterafce
enum Type {
IGNORE_CACHE, CACHE_ONLY, NETWORK_ONLY, NETWORK_ELSE_CACHE,
CACHE_ELSE_NETWORK, CACHE_THEN_NETWORK, IGNORE_CACHE, CACHE_ONLY,
NETWORK_ONLY, NETWORK_ELSE_CACHE, CACHE_ELSE_NETWORK, CACHE_THEN_NETWORK
}
enum Type {
IGNORE_CACHE, CACHE_ONLY, NETWORK_ONLY, NETWORK_ELSE_CACHE,
CACHE_ELSE_NETWORK, CACHE_THEN_NETWORK, IGNORE_CACHE, CACHE_ONLY,
NETWORK_ONLY, NETWORK_ELSE_CACHE, CACHE_ELSE_NETWORK, CACHE_THEN_NETWORK
}
Protected Types inherited from BmobQueryInterafce
enum DelegateType {
_bFIND_D, _bGET_D, _bCOUNT_D, _bSTATICS_D,
_bFIND_D, _bGET_D, _bCOUNT_D, _bSTATICS_D
}
enum DelegateType {
_bFIND_D, _bGET_D, _bCOUNT_D, _bSTATICS_D,
_bFIND_D, _bGET_D, _bCOUNT_D, _bSTATICS_D
}
Protected Attributes inherited from BmobQueryInterafce
BmobQueryInterafce::Type _queryType
BmobQueryInterafce::DelegateType _delegateType
std::vector< std::string > m_header
std::multimap< string,
cocos2d::CCObject * > m_whereData
string m_url
string m_order
string m_queryKey
string m_sum
string m_group
string m_min
string m_max
string m_average
bool m_isHaving
bool m_groupCount
int m_limit
int m_skip
Detailed Description
Definition at line 18 of file bmobquery.h.
Member Function Documentation
virtual void BmobQuery::addQueryKeys (string column) virtual
Parameters
column
Implements BmobQueryInterafce.
void BmobQuery::addQueryKeys (string column) virtual
Parameters
column
Implements BmobQueryInterafce.
Definition at line 296 of file bmobquery.cpp.
virtual void BmobQuery::addWhereContainedIn (string seg, CCObject * array) virtual
where
Parameters
seg
array
Implements BmobQueryInterafce.
void BmobQuery::addWhereContainedIn (string seg, CCObject * array) virtual
where
Parameters
seg
array
Implements BmobQueryInterafce.
Definition at line 188 of file bmobquery.cpp.
virtual void BmobQuery::addWhereContainsAll (string seg, CCArray * array) virtual
where
Parameters
seg
array
Implements BmobQueryInterafce.
void BmobQuery::addWhereContainsAll (string seg, CCArray * array) virtual
where
Parameters
seg
array
Implements BmobQueryInterafce.
Definition at line 214 of file bmobquery.cpp.
virtual void BmobQuery::addWhereDoesNotExists (string column) virtual
where
Parameters
column
Implements BmobQueryInterafce.
void BmobQuery::addWhereDoesNotExists (string column) virtual
where
Parameters
column
Implements BmobQueryInterafce.
Definition at line 255 of file bmobquery.cpp.
virtual void BmobQuery::addWhereEqualTo (string seg, CCObject * object) virtual
where
Parameters
seg
object name="Harrier"
Implements BmobQueryInterafce.
void BmobQuery::addWhereEqualTo (string seg, CCObject * object) virtual
where
Parameters
seg
object name="Harrier"
Implements BmobQueryInterafce.
Definition at line 109 of file bmobquery.cpp.
virtual void BmobQuery::addWhereExists (string column) virtual
where
Parameters
column
Implements BmobQueryInterafce.
void BmobQuery::addWhereExists (string column) virtual
where
Parameters
column
Implements BmobQueryInterafce.
Definition at line 243 of file bmobquery.cpp.
virtual void BmobQuery::addWhereGreaterThan (string seg, CCObject * object) virtual
where
Parameters
seg
object age>20
Implements BmobQueryInterafce.
void BmobQuery::addWhereGreaterThan (string seg, CCObject * object) virtual
where
Parameters
seg
object age>20
Implements BmobQueryInterafce.
Definition at line 162 of file bmobquery.cpp.
virtual void BmobQuery::addWhereGreaterThanOrEqualTo (string seg, CCObject * object) virtual
where
Parameters
seg
object age>=20
Implements BmobQueryInterafce.
void BmobQuery::addWhereGreaterThanOrEqualTo (string seg, CCObject * object) virtual
where
Parameters
seg
object age>=20
Implements BmobQueryInterafce.
Definition at line 175 of file bmobquery.cpp.
virtual void BmobQuery::addWhereLessThan (string seg, CCObject * object) virtual
where
Parameters
seg
object age<30
Implements BmobQueryInterafce.
void BmobQuery::addWhereLessThan (string seg, CCObject * object) virtual
where
Parameters
seg
object age<30
Implements BmobQueryInterafce.
Definition at line 136 of file bmobquery.cpp.
virtual void BmobQuery::addWhereLessThanOrEqualTo (string seg, CCObject * object) virtual
where
Parameters
seg
object age<=30
Implements BmobQueryInterafce.
void BmobQuery::addWhereLessThanOrEqualTo (string seg, CCObject * object) virtual
where
Parameters
seg
object age<=30
Implements BmobQueryInterafce.
Definition at line 149 of file bmobquery.cpp.
virtual void BmobQuery::addWhereNotContainedIn (string seg, CCObject * array) virtual
where
Parameters
seg
array
Implements BmobQueryInterafce.
void BmobQuery::addWhereNotContainedIn (string seg, CCObject * array) virtual
where
Parameters
seg
array
Implements BmobQueryInterafce.
Definition at line 201 of file bmobquery.cpp.
virtual void BmobQuery::addWhereNotEqualTo (string seg, CCObject * object) virtual
where
Parameters
seg
object name!="Harrier"
Implements BmobQueryInterafce.
void BmobQuery::addWhereNotEqualTo (string seg, CCObject * object) virtual
where
Parameters
seg
object name!="Harrier"
Implements BmobQueryInterafce.
Definition at line 118 of file bmobquery.cpp.
virtual void BmobQuery::average (string column) virtual
Parameters
column
Implements BmobQueryInterafce.
void BmobQuery::average (string column) virtual
Parameters
column
Implements BmobQueryInterafce.
Definition at line 305 of file bmobquery.cpp.
virtual void BmobQuery::count (BmobCountDelegate * delegate, bool sign = false) virtual
Parameters
delegate
sign
Implements BmobQueryInterafce.
void BmobQuery::count (BmobCountDelegate * delegate, bool sign = false) virtual
Parameters
delegate
sign
Implements BmobQueryInterafce.
Definition at line 70 of file bmobquery.cpp.
References BmobSDKInit::isInitialize(), and query().
virtual void BmobQuery::findObjects (BmobFindDelegate * delegate) virtual
Parameters
delegate
Implements BmobQueryInterafce.
virtual void BmobQuery::findObjects (string tableName, BmobFindDelegate * delegate) virtual
Parameters
tableName
delegate
Implements BmobQueryInterafce.
void BmobQuery::findObjects (BmobFindDelegate * delegate) virtual
Parameters
delegate
Implements BmobQueryInterafce.
Definition at line 19 of file bmobquery.cpp.
References BmobSDKInit::isInitialize(), and query().
void BmobQuery::findObjects (string tableName, BmobFindDelegate * delegate) virtual
Parameters
tableName
delegate
Implements BmobQueryInterafce.
Definition at line 35 of file bmobquery.cpp.
References BmobSDKInit::isInitialize(), and query().
virtual void BmobQuery::findStatistics (BmobStaticsDelegate * delegate) virtual
Parameters
delegate
Implements BmobQueryInterafce.
void BmobQuery::findStatistics (BmobStaticsDelegate * delegate) virtual
Parameters
delegate
Implements BmobQueryInterafce.
Definition at line 92 of file bmobquery.cpp.
References BmobSDKInit::isInitialize(), and query().
virtual vector<string> BmobQuery::getHeader () virtual
HTTP
Reimplemented from BmobQueryInterafce.
vector< string > BmobQuery::getHeader () virtual
HTTP
Reimplemented from BmobQueryInterafce.
Definition at line 340 of file bmobquery.cpp.
Referenced by query().
virtual void BmobQuery::getObject (string objectId, BmobGetDelegate * delegate) virtual
objectId
Parameters
objectid objectId
delegate
Implements BmobQueryInterafce.
void BmobQuery::getObject (string objectId, BmobGetDelegate * delegate) virtual
objectId
Parameters
objectid objectId
delegate
Implements BmobQueryInterafce.
Definition at line 51 of file bmobquery.cpp.
References BmobSDKInit::isInitialize(), and query().
virtual void BmobQuery::groupby (string column) virtual
Parameters
column
Implements BmobQueryInterafce.
void BmobQuery::groupby (string column) virtual
Parameters
column
Implements BmobQueryInterafce.
Definition at line 317 of file bmobquery.cpp.
virtual void BmobQuery::max (string column) virtual
Parameters
cloumn
Implements BmobQueryInterafce.
void BmobQuery::max (string column) virtual
Parameters
cloumn
Implements BmobQueryInterafce.
Definition at line 309 of file bmobquery.cpp.
virtual void BmobQuery::min (string column) virtual
Parameters
column
Implements BmobQueryInterafce.
void BmobQuery::min (string column) virtual
Parameters
column
Implements BmobQueryInterafce.
Definition at line 313 of file bmobquery.cpp.
virtual void BmobQuery::onHttpRequestCompleted (cocos2d::CCNode * pSender, void * data) protected virtual
HTTP
Implements BmobQueryInterafce.
void BmobQuery::onHttpRequestCompleted (cocos2d::CCNode * pSender, void * data) protected virtual
HTTP
Implements BmobQueryInterafce.
Definition at line 404 of file bmobquery.cpp.
References Json::Reader::parse().
Referenced by query().
virtual void BmobQuery::order (string key) virtual
Implements BmobQueryInterafce.
void BmobQuery::order (string key) virtual
Implements BmobQueryInterafce.
Definition at line 275 of file bmobquery.cpp.
virtual void BmobQuery::query () protected virtual
Implements BmobQueryInterafce.
void BmobQuery::query () protected virtual
Implements BmobQueryInterafce.
Definition at line 368 of file bmobquery.cpp.
References getHeader(), and onHttpRequestCompleted().
Referenced by count(), findObjects(), findStatistics(), and getObject().
virtual void BmobQuery::setHeader (vector< string > v) virtual
HTTP
Reimplemented from BmobQueryInterafce.
void BmobQuery::setHeader (vector< string > v) virtual
HTTP
Reimplemented from BmobQueryInterafce.
Definition at line 329 of file bmobquery.cpp.
virtual void BmobQuery::setLimit (int limit) virtual
Implements BmobQueryInterafce.
void BmobQuery::setLimit (int limit) virtual
Implements BmobQueryInterafce.
Definition at line 267 of file bmobquery.cpp.
virtual void BmobQuery::setSkip (int skip) virtual
Implements BmobQueryInterafce.
void BmobQuery::setSkip (int skip) virtual
Implements BmobQueryInterafce.
Definition at line 271 of file bmobquery.cpp.
virtual void BmobQuery::sum (string column) virtual
Parameters
column
Implements BmobQueryInterafce.
void BmobQuery::sum (string column) virtual
Parameters
column
Implements BmobQueryInterafce.
Definition at line 301 of file bmobquery.cpp.
virtual void BmobQuery::whereStartsWith () virtual
where excute
Implements BmobQueryInterafce.
void BmobQuery::whereStartsWith () virtual
where excute
Implements BmobQueryInterafce.
Definition at line 235 of file bmobquery.cpp.
The documentation for this class was generated from the following files:
baseobject/bmobquery.h
baseobject/bmobquery.cpp