Cocos2dx SDK: BmobSDKInit Class Reference
BmobSDKInit Class Reference
Static Public Member Functions
static void initialize (string app_id, string app_key)
static bool isInitialize ()
static void initialize (string app_id, string app_key)
static bool isInitialize ()
Static Public Attributes
static string APP_ID
static string APP_KEY
static string URL = BmobSDKInit::BASE_URL + "/1/classes/"
static string BASE_URL = "https://api.bmob.cn"
static string USER_URL = BmobSDKInit::BASE_URL + "/1/users"
static string LOGIN_URL = BmobSDKInit::BASE_URL + "/1/login"
static string USER_TABLE = "_User"
static string RESET_URL = BmobSDKInit::BASE_URL + "/1/requestPasswordReset"
static string REQUEST_SMS_CODE_URL = BmobSDKInit::BASE_URL + "/1/requestSmsCode"
static string RESET_BY_CODE_URL = BmobSDKInit::BASE_URL + "/1/resetPasswordBySmsCode"
static string UPDATE_PWD_URL = BmobSDKInit::BASE_URL + "/1/updateUserPassword"
static string EMAIL_VERIFY_URL = BmobSDKInit::BASE_URL + "/1/requestEmailVerify"
static string CLOUD_CODE_URL = BmobSDKInit::BASE_URL + "/1/functions/"
Detailed Description
Definition at line 14 of file bmobSDKinit.h.
Member Function Documentation
void BmobSDKInit::initialize (string app_id, string app_key) static
使用appID和appKey初始化环境
Definition at line 19 of file bmobSDKinit.cpp.
static void BmobSDKInit::initialize (string app_id, string app_key) static
initialize bmob sdk
static bool BmobSDKInit::isInitialize () static
test
bool BmobSDKInit::isInitialize () static
查询环境是否已经初始化
Definition at line 24 of file bmobSDKinit.cpp.
Referenced by BmobQuery::count(), BmobCloud::execCloudCode(), BmobQuery::findObjects(), BmobQuery::findStatistics(), BmobQuery::getObject(), and BmobObject::save().
The documentation for this class was generated from the following files:
baseobject/bmobSDKinit.h
baseobject/bmobSDKinit.cpp