Cocos2dx SDK: BmobCloud Class Reference
BmobCloud Class Reference
Public Types
enum EXEC_Type { EXEC_Exec, EXEC_Create, EXEC_Delete }
Public Member Functions
void execCloudCode (string cloudName, std::map< string, CCObject * > param, BmobCloudDelegate *delegate, BmobCloud::EXEC_Type type=EXEC_Type::EXEC_Exec)
Protected Member Functions
void send ()
void send (network::HttpRequest::Type type)
virtual void onHttpRequestCompleted (cocos2d::CCNode *pSender, void *data)
Detailed Description
Definition at line 22 of file bmobcloud.h.
Member Enumeration Documentation
enum BmobCloud::EXEC_Type
云端代码的操作类型，执行代码、创建代码、删除代码
Definition at line 27 of file bmobcloud.h.
Member Function Documentation
void BmobCloud::execCloudCode (string cloudName, std::map< string, CCObject * > param, BmobCloudDelegate * delegate, BmobCloud::EXEC_Type type = EXEC_Type::EXEC_Exec)
执行云端代码
Parameters
cloudName 云端代码的方法名，如果是创建代码，传递NULL
param 云端代码的参数
delegate 代码执行的回调函数
type (默认是EXEC_Exec) 执行的操作，执行代码、创建代码、删除代码 注：当执行创建云端代码的时候，参数中存储的是方法的主题，其中使用键值的对应关系 键为code，值是代码，param 仅存储一个值;如果调用的是创建代码，那么cloudName 传递NULL即可
Definition at line 95 of file bmobcloud.cpp.
References BmobSDKInit::isInitialize().
void BmobCloud::onHttpRequestCompleted (cocos2d::CCNode * pSender, void * data) protected virtual
HTTP请求回调函数
Parameters
pSender
data 回调返回数据
Definition at line 49 of file bmobcloud.cpp.
References Json::Reader::parse().
Referenced by send().
void BmobCloud::send () protected
发送请求给BmobSDK后台
Definition at line 16 of file bmobcloud.cpp.
void BmobCloud::send (network::HttpRequest::Type type) protected
使用HTTP类型发送请求
Parameters
type http请求类型,GET、POST、PUT、DELETE etc.
Definition at line 20 of file bmobcloud.cpp.
References onHttpRequestCompleted().
The documentation for this class was generated from the following files:
baseobject/bmobcloud.h
baseobject/bmobcloud.cpp