Cocos2dx SDK: Json::Reader Class Reference
Json::Reader Class Reference
Unserialize a JSON document into a Value.
#include <reader.h>
Public Types
typedef char Char
typedef const Char * Location
typedef char Char
typedef const Char * Location
Public Member Functions
Reader ()
Constructs a Reader allowing all features for parsing.
Reader (const Features &features)
Constructs a Reader allowing the specified feature set for parsing.
bool parse (const std::string &document, Value &root, bool collectComments=true)
Read a Value from a JSON document.
bool parse (const char *beginDoc, const char *endDoc, Value &root, bool collectComments=true)
Read a Value from a JSON document.
bool parse (std::istream &is, Value &root, bool collectComments=true)
Parse from input stream.
std::string getFormatedErrorMessages () const
Returns a user friendly string that list errors in the parsed document.
Reader ()
Constructs a Reader allowing all features for parsing.
Reader (const Features &features)
Constructs a Reader allowing the specified feature set for parsing.
bool parse (const std::string &document, Value &root, bool collectComments=true)
Read a Value from a JSON document.
bool parse (const char *beginDoc, const char *endDoc, Value &root, bool collectComments=true)
Read a Value from a JSON document.
bool parse (std::istream &is, Value &root, bool collectComments=true)
Parse from input stream.
std::string getFormatedErrorMessages () const
Returns a user friendly string that list errors in the parsed document.
Detailed Description
Unserialize a JSON document into a Value.
Definition at line 16 of file reader.h.
Member Function Documentation
std::string Json::Reader::getFormatedErrorMessages () const
Returns a user friendly string that list errors in the parsed document.
Returns
Formatted error message with the list of errors with their location in the parsed document. An empty string is returned if no error occurred during parsing.
Definition at line 858 of file json_reader.cpp.
Referenced by Json::operator>>().
std::string Json::Reader::getFormatedErrorMessages () const
Returns a user friendly string that list errors in the parsed document.
Returns
Formatted error message with the list of errors with their location in the parsed document. An empty string is returned if no error occurred during parsing.
bool Json::Reader::parse (const std::string & document, Value & root, bool collectComments = true)
Read a Value from a JSON document.
Parameters
document UTF-8 encoded string containing the document to read.
root [out] Contains the root value of the document if it was successfully parsed.
collectComments true to collect comment and allow writing them back during serialization, false to discard comments. This parameter is ignored if Features::allowComments_ is false.
Returns
true if the document was successfully parsed, false if an error occurred.
Definition at line 122 of file json_reader.cpp.
Referenced by BmobCloud::onHttpRequestCompleted(), BmobQuery::onHttpRequestCompleted(), BmobObject::onHttpRequestCompleted(), Json::operator>>(), and parse().
bool Json::Reader::parse (const std::string & document, Value & root, bool collectComments = true)
Read a Value from a JSON document.
Parameters
document UTF-8 encoded string containing the document to read.
root [out] Contains the root value of the document if it was successfully parsed.
collectComments true to collect comment and allow writing them back during serialization, false to discard comments. This parameter is ignored if Features::allowComments_ is false.
Returns
true if the document was successfully parsed, false if an error occurred.
bool Json::Reader::parse (const char * beginDoc, const char * endDoc, Value & root, bool collectComments = true)
Read a Value from a JSON document.
Parameters
document UTF-8 encoded string containing the document to read.
root [out] Contains the root value of the document if it was successfully parsed.
collectComments true to collect comment and allow writing them back during serialization, false to discard comments. This parameter is ignored if Features::allowComments_ is false.
Returns
true if the document was successfully parsed, false if an error occurred.
Definition at line 151 of file json_reader.cpp.
References Json::Features::allowComments_, Json::commentAfter, Json::Value::setComment(), and Json::Features::strictRoot_.
bool Json::Reader::parse (const char * beginDoc, const char * endDoc, Value & root, bool collectComments = true)
Read a Value from a JSON document.
Parameters
document UTF-8 encoded string containing the document to read.
root [out] Contains the root value of the document if it was successfully parsed.
collectComments true to collect comment and allow writing them back during serialization, false to discard comments. This parameter is ignored if Features::allowComments_ is false.
Returns
true if the document was successfully parsed, false if an error occurred.
bool Json::Reader::parse (std::istream & is, Value & root, bool collectComments = true)
Parse from input stream.
See Also
Json::operator>>(std::istream&, Json::Value&).
Definition at line 134 of file json_reader.cpp.
References parse().
bool Json::Reader::parse (std::istream & is, Value & root, bool collectComments = true)
Parse from input stream.
See Also
Json::operator>>(std::istream&, Json::Value&).
The documentation for this class was generated from the following files:
jsoncpp/include/reader.h
jsoncpp/src/json_reader.cpp