Cocos2dx SDK: Json Namespace Reference
Json Namespace Reference
JSON (JavaScript Object Notation).
Data Structures
class Features
Configuration passed to reader and writer. This configuration object can be used to force the Reader or Writer to behave in a standard conforming way.
class Reader
Unserialize a JSON document into a Value.
class StaticString
Lightweight wrapper to tag static string.
class Value
Represents a JSON value.
class PathArgument
Experimental and untested: represents an element of the "path" to access a node.
class Path
Experimental and untested: represents a "path" to access a node.
class ValueAllocator
Experimental do not use: Allocator to customize member name and string value memory management done by Value.
class ValueIteratorBase
base class for Value iterators.
class ValueConstIterator
const iterator for object and array value.
class ValueIterator
Iterator for object and array value.
class Writer
Abstract class for writers.
class FastWriter
Outputs a Value in JSON format without formatting (not human friendly).
class StyledWriter
Writes a Value in JSON format in a human friendly way.
class StyledStreamWriter
Writes a Value in JSON format in a human friendly way, to a stream rather than to a string.
class BatchAllocator
class DefaultValueAllocator
struct DummyValueAllocatorInitializer
Typedefs
typedef int Int
typedef unsigned int UInt
Enumerations
enum ValueType {
nullValue = 0, intValue, uintValue, realValue,
stringValue, booleanValue, arrayValue, objectValue,
nullValue = 0, intValue, uintValue, realValue,
stringValue, booleanValue, arrayValue, objectValue
}
Type of the value held by a Value object.
enum CommentPlacement {
commentBefore = 0, commentAfterOnSameLine, commentAfter, numberOfCommentPlacement,
commentBefore = 0, commentAfterOnSameLine, commentAfter, numberOfCommentPlacement
}
enum ValueType {
nullValue = 0, intValue, uintValue, realValue,
stringValue, booleanValue, arrayValue, objectValue,
nullValue = 0, intValue, uintValue, realValue,
stringValue, booleanValue, arrayValue, objectValue
}
Type of the value held by a Value object.
enum CommentPlacement {
commentBefore = 0, commentAfterOnSameLine, commentAfter, numberOfCommentPlacement,
commentBefore = 0, commentAfterOnSameLine, commentAfter, numberOfCommentPlacement
}
Functions
std::istream & operator>> (std::istream &, Value &)
Read from 'sin' into 'root'.
std::string JSON_API valueToString (Int value)
std::string JSON_API valueToString (UInt value)
std::string JSON_API valueToString (double value)
std::string JSON_API valueToString (bool value)
std::string JSON_API valueToQuotedString (const char *value)
std::ostream & operator<< (std::ostream &, const Value &root)
Output using the StyledStreamWriter.
Detailed Description
JSON (JavaScript Object Notation).
Enumeration Type Documentation
enum Json::CommentPlacement
Enumerator
commentBefore
a comment placed on the line before a value
commentAfterOnSameLine
a comment just after a value on the same line
commentAfter
a comment on the line after a value (only make sense for root value)
commentBefore
a comment placed on the line before a value
commentAfterOnSameLine
a comment just after a value on the same line
commentAfter
a comment on the line after a value (only make sense for root value)
Definition at line 35 of file value.h.
enum Json::CommentPlacement
Enumerator
commentBefore
a comment placed on the line before a value
commentAfterOnSameLine
a comment just after a value on the same line
commentAfter
a comment on the line after a value (only make sense for root value)
commentBefore
a comment placed on the line before a value
commentAfterOnSameLine
a comment just after a value on the same line
commentAfter
a comment on the line after a value (only make sense for root value)
Definition at line 35 of file value.h.
enum Json::ValueType
Type of the value held by a Value object.
Enumerator
nullValue
'null' value
intValue
signed integer value
uintValue
unsigned integer value
realValue
double value
stringValue
UTF-8 string value.
booleanValue
bool value
arrayValue
array value (ordered list)
objectValue
object value (collection of name/value pairs).
nullValue
'null' value
intValue
signed integer value
uintValue
unsigned integer value
realValue
double value
stringValue
UTF-8 string value.
booleanValue
bool value
arrayValue
array value (ordered list)
objectValue
object value (collection of name/value pairs).
Definition at line 23 of file value.h.
enum Json::ValueType
Type of the value held by a Value object.
Enumerator
nullValue
'null' value
intValue
signed integer value
uintValue
unsigned integer value
realValue
double value
stringValue
UTF-8 string value.
booleanValue
bool value
arrayValue
array value (ordered list)
objectValue
object value (collection of name/value pairs).
nullValue
'null' value
intValue
signed integer value
uintValue
unsigned integer value
realValue
double value
stringValue
UTF-8 string value.
booleanValue
bool value
arrayValue
array value (ordered list)
objectValue
object value (collection of name/value pairs).
Definition at line 23 of file value.h.
Function Documentation
std::ostream & Json::operator<< (std::ostream & sout, const Value & root)
Output using the StyledStreamWriter.
See Also
Json::operator>>()
Definition at line 821 of file json_writer.cpp.
References Json::StyledStreamWriter::write().
std::istream & Json::operator>> (std::istream & sin, Value & root)
Read from 'sin' into 'root'.
Always keep comments from the input JSON.
This can be used to read a file into a particular sub-object. For example:
Json::Value root;
cin >> root["dir"]["file"];
cout << root;
Result:
{
"dir": {
    "file": {
    // The input stream JSON would be nested here.
    }
}
}
Exceptions
std::exception on parse error.
See Also
Json::operator<<()
Definition at line 875 of file json_reader.cpp.
References Json::Reader::getFormatedErrorMessages(), and Json::Reader::parse().